version: "3.8"
networks:
  backend:
  frontend:
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
  db_postgresql:
    container_name: postgresql_container
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_development}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    restart: always
    image: redis:7-alpine
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - db-data:/app/db
    working_dir: /app
    environment:
      FORCE_DB_CREATE: ${FORCE_DB_CREATE}
      FORCE_DB_SEED: ${FORCE_DB_SEED}
      APPLICATION_NAME: ${APPLICATION_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${PORT}
      JWT_KEY: ${JWT_KEY}
      BUNDLE_GEMFILE: /app/Gemfile
      REDIS_URL: redis://redis:6379/1
    command: bin/docker-dev-start-web.sh
    networks:
      - backend
      - frontend
    ports:
      - "3000:3000"
    depends_on:
      - db_postgresql
      - redis
volumes:
  bundle:
  postgres_data:
  db-data:
